# Named profiles for filter_coco_category_wrap.py
# Use:
#   python3 filter_coco_category_wrap.py --config-name <profile_name>
# or:
#   python3 filter_coco_category_wrap.py --config-file /path/to/xxx.toml --config-name <profile_name>

[profiles.demo_by_name]
category_names = "boom"
# json_dir = "/home/ieds/datasets/nfs6399/dataset/work/labels/coco/object_model"
json_file = "/home/ieds/datasets/nfs6399/dataset/work/labels/coco/object_model/test.json"
label_root = "/home/ieds/datasets/nfs6399/dataset/work/labels/yolo/object_model"
output_root = "/home/ieds/Pictures/boom_nfs6399"
merge = "false"
dry_run = true
debug = true

[profiles.demo_by_id]
category_ids = "1"
json_file = "/path/to/train.json"
label_root = "/path/to/labels/yolo/object_model"
output_root = "/path/to/output"
merge = "false"
dry_run = false
debug = false
